### ISSUE TITLE
error: ‘to_array’ is not a member of ‘std’

### ISSUE THREAD

**Issue by SteveLee123** [qqiangwu/cppsafe#38]
when I excuate this command `cmake --build build -j`
I met this error:
```
/usr2/l00807026/l30042995/cppsafe/cppsafe/lib/lifetime/LifetimeTypeCategory.cpp:606:53: error: ‘to_array’ is not a member of ‘std’; did you mean ‘is_array’?
  606 |             static constexpr auto MapConstFn = std::to_array<StringRef>({
      |                                                     ^~~~~~~~
      |                                                     is_array

```

how can I solve it ?

**Comment by qqiangwu** [comment]
it seems your compiler version does not support C++20 well. `std::to_array` is a C++20 feature and is supported by at least gcc10 and clang10

**Comment by SteveLee123** [comment]
I have gcc-9.4.0 and clang-10 on my Linux.

how can I specify the clang-10 as the compiler?

**Comment by qqiangwu** [comment]
search for cmake usage: https://stackoverflow.com/questions/45933732/how-to-specify-a-compiler-in-cmake

**Comment by SteveLee123** [comment]
finally fix by update my gcc. thanks.
